name: Build and Test

on: workflow_call

jobs:
  for-node:
    name: For Node.js

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Upgrade NPM
        run: npm install -g npm@9

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test setup
        run: npm run dev:postgres

      - name: Test
        run: npm test
